[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist/phone-shop-frontend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
