const ROLE_PERMISSIONS = {
  ADMIN: [
    'PRODUCT_VIEW','PRODUCT_CREATE','PRODUCT_UPDATE','PRODUCT_DELETE',
    'ORDER_VIEW','ORDER_UPDATE','ORDER_CANCEL',
    'USER_VIEW','USER_CREATE','USER_UPDATE','USER_DELETE',
    'PAYMENT_VIEW','PAYMENT_REFUND',
    'REPORT_VIEW','REPORT_EXPORT',
    'ROLE_VIEW','ROLE_UPDATE',
    'COUPON_MANAGE'
  ],
  MANAGER: [
    'PRODUCT_VIEW','PRODUCT_CREATE','PRODUCT_UPDATE',
    'ORDER_VIEW','ORDER_UPDATE',
    'USER_VIEW',
    'REPORT_VIEW'
  ],
  STAFF: [
    'PRODUCT_VIEW','ORDER_VIEW','ORDER_UPDATE'
  ],
  CUSTOMER: []
};

module.exports = { ROLE_PERMISSIONS };
